package generator

const codeTemplateHead = `
// Code generated by protoc-gen-redis. DO NOT EDIT.

package {{.PackageName}}

import (
	{{range .Imports}} "{{.}}"
	{{end}}
)

`

const codeTemplateEnums = `
{{range $e := .Enums}}
// Enum {{$e.Name}}
type {{$e.Name}} int32

const (
	{{- range $v := $e.Values}}
	{{$v.Name}} {{$e.Name}} = {{$v.Value}}
	{{- end}}
)
{{end}}
`

// codeTemplateProtoHelpers 是 protobuf wire format 的辅助函数，
// 文件内存在 message 或集合字段时随文件头输出一次（redisProto 前缀避免与用户代码冲突）。
// 编码规则与 protobuf 规范一致：tag = field<<3 | wireType，
// wireType：0=varint，1=fixed64，2=length-delimited，5=fixed32。
const codeTemplateProtoHelpers = `
// --- protobuf wire format 辅助函数（语言无关序列化，规则见 https://protobuf.dev/programming-guides/encoding/） ---

// redisProtoAppendVarint 追加一个 base-128 varint 编码的 uint64
func redisProtoAppendVarint(buf []byte, v uint64) []byte {
	for v >= 0x80 {
		buf = append(buf, byte(v)|0x80)
		v >>= 7
	}
	return append(buf, byte(v))
}

// redisProtoReadVarint 读取一个 varint，返回（值，消耗字节数）
func redisProtoReadVarint(b []byte) (uint64, int, error) {
	var v uint64
	for i := 0; i < len(b) && i < 10; i++ {
		v |= uint64(b[i]&0x7F) << (7 * i)
		if b[i]&0x80 == 0 {
			return v, i + 1, nil
		}
	}
	return 0, 0, fmt.Errorf("protobuf varint 读取失败: 数据截断或过长")
}

// redisProtoAppendTag 追加字段 tag（field<<3 | wireType）
func redisProtoAppendTag(buf []byte, field, wire int32) []byte {
	return redisProtoAppendVarint(buf, uint64(field)<<3|uint64(wire))
}

// redisProtoAppendLen 追加 length-delimited 数据（长度前缀 + 数据）
func redisProtoAppendLen(buf, payload []byte) []byte {
	buf = redisProtoAppendVarint(buf, uint64(len(payload)))
	return append(buf, payload...)
}

// redisProtoReadBytes 读取 length-delimited 数据，返回（数据拷贝，消耗字节数）；
// 返回拷贝避免与输入缓冲区 alias。
func redisProtoReadBytes(b []byte) ([]byte, int, error) {
	n, k, err := redisProtoReadVarint(b)
	if err != nil {
		return nil, 0, err
	}
	if n > uint64(len(b)-k) {
		return nil, 0, fmt.Errorf("protobuf length-delimited 数据截断: 期望 %d 字节, 剩余 %d", n, len(b)-k)
	}
	return append([]byte(nil), b[k:k+int(n)]...), k + int(n), nil
}

// redisProtoAppendFixed32 追加小端 4 字节
func redisProtoAppendFixed32(buf []byte, v uint32) []byte {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24))
}

// redisProtoReadFixed32 读取小端 4 字节
func redisProtoReadFixed32(b []byte) (uint32, int, error) {
	if len(b) < 4 {
		return 0, 0, fmt.Errorf("protobuf fixed32 数据截断")
	}
	return uint32(b[0]) | uint32(b[1])<<8 | uint32(b[2])<<16 | uint32(b[3])<<24, 4, nil
}

// redisProtoAppendFixed64 追加小端 8 字节
func redisProtoAppendFixed64(buf []byte, v uint64) []byte {
	return append(buf,
		byte(v), byte(v>>8), byte(v>>16), byte(v>>24),
		byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
}

// redisProtoReadFixed64 读取小端 8 字节
func redisProtoReadFixed64(b []byte) (uint64, int, error) {
	if len(b) < 8 {
		return 0, 0, fmt.Errorf("protobuf fixed64 数据截断")
	}
	var v uint64
	for i := 0; i < 8; i++ {
		v |= uint64(b[i]) << (8 * i)
	}
	return v, 8, nil
}

// redisProtoSkip 跳过未知字段，返回消耗字节数
func redisProtoSkip(b []byte, wire uint64) (int, error) {
	switch wire {
	case 0: // varint
		_, n, err := redisProtoReadVarint(b)
		return n, err
	case 1: // fixed64
		if len(b) < 8 {
			return 0, fmt.Errorf("protobuf fixed64 数据截断")
		}
		return 8, nil
	case 2: // length-delimited
		_, n, err := redisProtoReadBytes(b)
		return n, err
	case 5: // fixed32
		if len(b) < 4 {
			return 0, fmt.Errorf("protobuf fixed32 数据截断")
		}
		return 4, nil
	default:
		return 0, fmt.Errorf("protobuf 未知 wire type %d", wire)
	}
}

`

// codeTemplate 按 message 生成 Redis 存取代码。
// 字段的 protobuf 编码/解码逻辑抽成 fieldEncode / fieldDecode 两个模板块，
// 整体序列化（MarshalRedisProto / UnmarshalRedisProto）与集合字段（map/repeated）
// 的字段级序列化方法（MarshalRedisProto<Field> / UnmarshalRedisProto<Field>）共用同一份逻辑。
const codeTemplate = `
// {{.FieldType}} 用于标识 Redis Hash 中的字段编号
type {{.FieldType}} uint32

{{range .Fields}}
// {{$.FieldType}}_{{.Name}} 是字段 {{.Name}} 对应的 Redis Hash field 编号
const {{$.FieldType}}_{{.Name}} {{$.FieldType}} = {{.ProtoTag}}
{{end}}

// {{.FieldType}}IDs 是所有字段编号常量的集合，类型为 []{{.FieldType}}
var {{.FieldType}}IDs = []{{.FieldType}}{
	{{range .Fields}}{{$.FieldType}}_{{.Name}},
	{{end}}
}

// {{.MessageName}} 提供针对 {{.MessageName}} 消息的 Redis 存取操作
type {{.MessageName}} struct {
	{{range .Fields}}
	{{.Name}} {{.GoType}}
	{{end}}
}

// New{{.MessageName}} 创建一个新的 {{.MessageName}} 实例
func New{{.MessageName}}() *{{.MessageName}} {
	return &{{.MessageName}}{}
}

// MarshalRedisProto 将 {{.MessageName}} 序列化为 protobuf wire format 字节流。
// 字节流与语言无关：任何语言使用同一份 .proto 定义即可解析。
// 编码遵循 proto3 语义：零值标量/空字符串/空 bytes 不编码，message 字段恒编码，
// repeated 逐元素编码（含零值），map 每键值对编码为子消息（field 1=key, field 2=value）。
func (p *{{.MessageName}}) MarshalRedisProto() ([]byte, error) {
	var buf []byte
{{range .Fields}}{{template "fieldEncode" .}}{{end}}
	return buf, nil
}

// UnmarshalRedisProto 从 protobuf wire format 字节流反序列化到 {{.MessageName}}。
// 反序列化前会先重置自身；未知字段跳过，缺失字段保持零值（proto3 语义）。
func (p *{{.MessageName}}) UnmarshalRedisProto(b []byte) error {
	*p = {{.MessageName}}{}
	for len(b) > 0 {
		tag, n, err := redisProtoReadVarint(b)
		if err != nil {
			return fmt.Errorf("protobuf 读取字段 tag 失败: %v", err)
		}
		b = b[n:]
		field := tag >> 3
		wire := tag & 7
		switch field {
		{{range .Fields}}
		case {{.ProtoTag}}: // {{.Name}}
{{template "fieldDecode" .}}
		{{end}}
		default:
			n, err = redisProtoSkip(b, wire)
			if err != nil {
				return err
			}
			b = b[n:]
		}
	}
	return nil
}

{{range .Fields}}
{{if or (eq .Kind "map") (eq .Kind "slice")}}
// MarshalRedisProto{{.Name}} 将字段 {{.Name}}（集合字段）整体序列化为 protobuf wire format 字节，
// 即 {{.Name}} 在 Redis Hash 中的值（hash field = tag {{.ProtoTag}}）
func (p *{{$.MessageName}}) MarshalRedisProto{{.Name}}() ([]byte, error) {
	var buf []byte
{{template "fieldEncode" .}}
	return buf, nil
}

// UnmarshalRedisProto{{.Name}} 从 {{.Name}} 字段的 protobuf wire format 字节反序列化
// （字节须为 MarshalRedisProto{{.Name}} 的输出，或等价的单字段 protobuf 编码）
func (p *{{$.MessageName}}) UnmarshalRedisProto{{.Name}}(b []byte) error {
	p.{{.Name}} = nil
	for len(b) > 0 {
		tag, n, err := redisProtoReadVarint(b)
		if err != nil {
			return err
		}
		if tag>>3 != {{.ProtoTag}} {
			return fmt.Errorf("protobuf 字段 %s tag 不匹配: %d", "{{.Name}}", tag>>3)
		}
		b = b[n:]
		{
			wire := tag & 7
{{template "fieldDecode" .}}
		}
	}
	return nil
}
{{end}}
{{end}}

// GetFields 从 Redis Hash 中读取指定字段的值，填充到当前结构体实例中
// conn: Redis 连接
// REDBKey: 业务维度 Key
// ida, idb: 用于组成唯一 Hash Key 的两个 uint64 分片维度
// fields: 要读取的字段编号列表，如 {{.FieldType}}_Name, {{.FieldType}}_Age
//          如果 fields 为空（长度为 0），则默认读取所有字段（即 {{.FieldType}}IDs）
//          集合字段（map/repeated）整体 protobuf 反序列化
func (p *{{.MessageName}}) GetFields(conn redis.Conn, REDBKey uint32, ida, idb uint64, fields ...{{.FieldType}}) error {
	key := fmt.Sprintf({{printf "%q" .KeyFormat}}, REDBKey, ida, idb)

	// 决定要操作的字段列表
	fieldsToUse := fields
	if len(fieldsToUse) == 0 {
		fieldsToUse = {{.FieldType}}IDs
	}

	// 构造 HMGET 参数：key + fieldID1 + fieldID2 + ...，一次取回全部字段值
	args := []interface{}{key}
	for _, fieldID := range fieldsToUse {
		args = append(args, fieldID)
	}

	// 一次 HMGET 获取所有字段值
	reply, err := conn.Do("HMGET", args...)
	if err != nil {
		return fmt.Errorf("HMGET 失败: %v", err)
	}

	// 解析返回的 []interface{} 列表
	values, err := redis.Values(reply, nil)
	if err != nil {
		return fmt.Errorf("解析 HMGET 结果失败: %v", err)
	}

	// 逐一处理每个字段
	fieldIndex := 0
	for _, fieldID := range fieldsToUse {
		switch fieldID {
		{{range .Fields}}
		case {{$.FieldType}}_{{.Name}}:
			{{if eq .Kind "plain"}}
			{{if .IsMsg}}
			// --- Protobuf 反序列化字段: {{.Name}} ---
			if val, ok := values[fieldIndex].([]byte); ok && val != nil {
				if err := p.{{.Name}}.UnmarshalRedisProto(val); err != nil {
					return fmt.Errorf("protobuf 反序列化字段 %s 失败: %v", "{{.Name}}", err)
				}
			}
			{{else}}
			// --- 直读字段: {{.Name}} ---
			if val, ok := values[fieldIndex].([]byte); ok && val != nil {
				{{if .IsEnum}}
				intValue, err := strconv.ParseInt(string(val), 10, 64)
				if err != nil {
					return fmt.Errorf("解析枚举字段 %s 失败: %v", "{{.Name}}", err)
				}
				p.{{.Name}} = {{.GoType}}(int32(intValue))
				{{else if eq .GoType "string"}}
				p.{{.Name}} = string(val)
				{{else if eq .GoType "uint64"}}
				id, err := strconv.ParseUint(string(val), 10, 64)
				if err != nil {
					return fmt.Errorf("解析字段 %s 失败: %v", "{{.Name}}", err)
				}
				p.{{.Name}} = id
				{{else if eq .GoType "int64"}}
				id, err := strconv.ParseInt(string(val), 10, 64)
				if err != nil {
					return fmt.Errorf("解析字段 %s 失败: %v", "{{.Name}}", err)
				}
				p.{{.Name}} = id
				{{else if eq .GoType "uint32"}}
				id, err := strconv.ParseUint(string(val), 10, 32)
				if err != nil {
					return fmt.Errorf("解析字段 %s 失败: %v", "{{.Name}}", err)
				}
				p.{{.Name}} = uint32(id)
				{{else if eq .GoType "int32"}}
				id, err := strconv.ParseInt(string(val), 10, 32)
				if err != nil {
					return fmt.Errorf("解析字段 %s 失败: %v", "{{.Name}}", err)
				}
				p.{{.Name}} = int32(id)
				{{else if eq .GoType "float64"}}
				f, err := strconv.ParseFloat(string(val), 64)
				if err != nil {
					return fmt.Errorf("解析字段 %s 失败: %v", "{{.Name}}", err)
				}
				p.{{.Name}} = f
				{{else if eq .GoType "float32"}}
				f, err := strconv.ParseFloat(string(val), 32)
				if err != nil {
					return fmt.Errorf("解析字段 %s 失败: %v", "{{.Name}}", err)
				}
				p.{{.Name}} = float32(f)
				{{else if eq .GoType "bool"}}
				if len(val) > 0 && val[0] == '1' {
					p.{{.Name}} = true
				} else if len(val) > 0 && val[0] == '0' {
					p.{{.Name}} = false
				}
				{{else if eq .GoType "[]byte"}}
				p.{{.Name}} = val
				{{else}}
				// 兜底：尝试字符串
				p.{{.Name}} = string(val)
				{{end}}
			}
			{{end}}
			{{else}}
			// --- 集合字段: {{.Name}}（整体 protobuf 反序列化）---
			if val, ok := values[fieldIndex].([]byte); ok && val != nil {
				if err := p.UnmarshalRedisProto{{.Name}}(val); err != nil {
					return fmt.Errorf("protobuf 反序列化字段 %s 失败: %v", "{{.Name}}", err)
				}
			}
			{{end}}
		{{end}}
		default:
			return fmt.Errorf("未知字段编号: %d", fieldID)
		}
		fieldIndex++
	}

	return nil
}

// SetFields 将当前结构体实例的字段值，存储到 Redis Hash 中
// conn: Redis 连接
// REDBKey: 业务维度 Key
// ida, idb: 用于组成唯一 Hash Key 的两个 uint64 分片维度
// fields: 要存储的字段编号列表，如 {{.FieldType}}_Name, {{.FieldType}}_Age
//          如果 fields 为空（长度为 0），则默认存储所有字段（即 {{.FieldType}}IDs）
//          集合字段（map/repeated）整体 protobuf 序列化后写入
func (p *{{.MessageName}}) SetFields(conn redis.Conn, REDBKey uint32, ida, idb uint64, fields ...{{.FieldType}}) error {
	key := fmt.Sprintf({{printf "%q" .KeyFormat}}, REDBKey, ida, idb)
	args := []interface{}{key}

	// 决定要操作的字段列表
	fieldsToUse := fields
	if len(fieldsToUse) == 0 {
		fieldsToUse = {{.FieldType}}IDs
	}

	for _, fieldID := range fieldsToUse {
		switch fieldID {
		{{range .Fields}}
		case {{$.FieldType}}_{{.Name}}:
			{{if eq .Kind "plain"}}
			{{if .IsMsg}}
			// --- Protobuf 序列化字段: {{.Name}} ---
			{
				b, err := p.{{.Name}}.MarshalRedisProto()
				if err != nil {
					return fmt.Errorf("protobuf 序列化字段 %s 失败: %v", "{{.Name}}", err)
				}
				args = append(args, fieldID, b)
			}
			{{else}}
			// --- 直存字段: {{.Name}} ---
			args = append(args, fieldID, p.{{.Name}})
			{{end}}
			{{else}}
			// --- 集合字段: {{.Name}}（整体 protobuf 序列化）---
			b, err := p.MarshalRedisProto{{.Name}}()
			if err != nil {
				return fmt.Errorf("protobuf 序列化字段 %s 失败: %v", "{{.Name}}", err)
			}
			args = append(args, fieldID, b)
			{{end}}
		{{end}}
		default:
			return fmt.Errorf("未知字段编号: %d", fieldID)
		}
	}

	// 所有字段统一一次 HSET 写入
	if len(args) > 1 {
		_, err := conn.Do("HSET", args...)
		return err
	}
	return nil
}

// ---------- 字段级 protobuf 编码/解码模板块（MarshalRedisProto / UnmarshalRedisProto
// 与集合字段的字段级序列化方法共用） ----------
//
// 约定上下文变量：fieldEncode 向 buf 追加字节；fieldDecode 从 b 消费一个字段段，
// 校验 wire 变量，解码结果写入 p.<Name>。

{{define "fieldEncode"}}
	// 字段 {{.Name}}（tag {{.ProtoTag}}）
{{if eq .Kind "plain"}}
{{if .IsMsg}}
{
	b, err := p.{{.Name}}.MarshalRedisProto()
	if err != nil {
		return nil, fmt.Errorf("protobuf 序列化字段 %s 失败: %v", "{{.Name}}", err)
	}
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 2)
	buf = redisProtoAppendLen(buf, b)
}
{{else if eq .GoType "string"}}
if p.{{.Name}} != "" {
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 2)
	buf = redisProtoAppendLen(buf, []byte(p.{{.Name}}))
}
{{else if eq .GoType "[]byte"}}
if len(p.{{.Name}}) > 0 {
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 2)
	buf = redisProtoAppendLen(buf, p.{{.Name}})
}
{{else if eq .GoType "float32"}}
if p.{{.Name}} != 0 {
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 5)
	buf = redisProtoAppendFixed32(buf, math.Float32bits(p.{{.Name}}))
}
{{else if eq .GoType "float64"}}
if p.{{.Name}} != 0 {
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 1)
	buf = redisProtoAppendFixed64(buf, math.Float64bits(p.{{.Name}}))
}
{{else if eq .GoType "bool"}}
if p.{{.Name}} {
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 0)
	buf = redisProtoAppendVarint(buf, 1)
}
{{else}}
// 枚举与整型（varint）
if p.{{.Name}} != 0 {
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 0)
	buf = redisProtoAppendVarint(buf, uint64(p.{{.Name}}))
}
{{end}}
{{else if eq .Kind "slice"}}
{{if .ElemIsMsg}}
for _, v := range p.{{.Name}} {
	b, err := v.MarshalRedisProto()
	if err != nil {
		return nil, fmt.Errorf("protobuf 序列化字段 %s 失败: %v", "{{.Name}}", err)
	}
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 2)
	buf = redisProtoAppendLen(buf, b)
}
{{else if eq .ElemType "string"}}
for _, v := range p.{{.Name}} {
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 2)
	buf = redisProtoAppendLen(buf, []byte(v))
}
{{else if eq .ElemType "[]byte"}}
for _, v := range p.{{.Name}} {
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 2)
	buf = redisProtoAppendLen(buf, v)
}
{{else if eq .ElemType "float32"}}
for _, v := range p.{{.Name}} {
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 5)
	buf = redisProtoAppendFixed32(buf, math.Float32bits(v))
}
{{else if eq .ElemType "float64"}}
for _, v := range p.{{.Name}} {
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 1)
	buf = redisProtoAppendFixed64(buf, math.Float64bits(v))
}
{{else}}
// 枚举与整型元素（varint）
for _, v := range p.{{.Name}} {
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 0)
	buf = redisProtoAppendVarint(buf, uint64(v))
}
{{end}}
{{else if eq .Kind "map"}}
for k, v := range p.{{.Name}} {
	var entry []byte
{{if eq .KeyType "string"}}
	entry = redisProtoAppendTag(entry, 1, 2)
	entry = redisProtoAppendLen(entry, []byte(k))
{{else if eq .KeyType "bool"}}
	entry = redisProtoAppendTag(entry, 1, 0)
	if k {
		entry = redisProtoAppendVarint(entry, 1)
	}
{{else}}
	entry = redisProtoAppendTag(entry, 1, 0)
	entry = redisProtoAppendVarint(entry, uint64(k))
{{end}}
{{if .ElemIsMsg}}
	b, err := v.MarshalRedisProto()
	if err != nil {
		return nil, fmt.Errorf("protobuf 序列化字段 %s 失败: %v", "{{.Name}}", err)
	}
	entry = redisProtoAppendTag(entry, 2, 2)
	entry = redisProtoAppendLen(entry, b)
{{else if eq .ElemType "string"}}
	entry = redisProtoAppendTag(entry, 2, 2)
	entry = redisProtoAppendLen(entry, []byte(v))
{{else if eq .ElemType "[]byte"}}
	entry = redisProtoAppendTag(entry, 2, 2)
	entry = redisProtoAppendLen(entry, v)
{{else if eq .ElemType "float32"}}
	entry = redisProtoAppendTag(entry, 2, 5)
	entry = redisProtoAppendFixed32(entry, math.Float32bits(v))
{{else if eq .ElemType "float64"}}
	entry = redisProtoAppendTag(entry, 2, 1)
	entry = redisProtoAppendFixed64(entry, math.Float64bits(v))
{{else}}
	// 枚举与整型值（varint）
	entry = redisProtoAppendTag(entry, 2, 0)
	entry = redisProtoAppendVarint(entry, uint64(v))
{{end}}
	buf = redisProtoAppendTag(buf, {{.ProtoTag}}, 2)
	buf = redisProtoAppendLen(buf, entry)
}
{{end}}
{{end}}

{{define "fieldDecode"}}
{{if eq .Kind "plain"}}
{{if .IsMsg}}
if wire != 2 {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
v, n, err := redisProtoReadBytes(b)
if err != nil {
	return err
}
b = b[n:]
if err := p.{{.Name}}.UnmarshalRedisProto(v); err != nil {
	return fmt.Errorf("protobuf 反序列化字段 %s 失败: %v", "{{.Name}}", err)
}
{{else if eq .GoType "string"}}
if wire != 2 {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
v, n, err := redisProtoReadBytes(b)
if err != nil {
	return err
}
b = b[n:]
p.{{.Name}} = string(v)
{{else if eq .GoType "[]byte"}}
if wire != 2 {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
v, n, err := redisProtoReadBytes(b)
if err != nil {
	return err
}
b = b[n:]
p.{{.Name}} = v
{{else if eq .GoType "float32"}}
if wire != 5 {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
v, n, err := redisProtoReadFixed32(b)
if err != nil {
	return err
}
b = b[n:]
p.{{.Name}} = math.Float32frombits(v)
{{else if eq .GoType "float64"}}
if wire != 1 {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
v, n, err := redisProtoReadFixed64(b)
if err != nil {
	return err
}
b = b[n:]
p.{{.Name}} = math.Float64frombits(v)
{{else if eq .GoType "bool"}}
if wire != 0 {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
v, n, err := redisProtoReadVarint(b)
if err != nil {
	return err
}
b = b[n:]
p.{{.Name}} = v != 0
{{else}}
// 枚举与整型（varint）
if wire != 0 {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
v, n, err := redisProtoReadVarint(b)
if err != nil {
	return err
}
b = b[n:]
p.{{.Name}} = {{.GoType}}(v)
{{end}}
{{else if eq .Kind "slice"}}
{{if .ElemIsMsg}}
if wire != 2 {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
v, n, err := redisProtoReadBytes(b)
if err != nil {
	return err
}
b = b[n:]
var elem {{.ElemType}}
if err := elem.UnmarshalRedisProto(v); err != nil {
	return fmt.Errorf("protobuf 反序列化字段 %s 失败: %v", "{{.Name}}", err)
}
p.{{.Name}} = append(p.{{.Name}}, elem)
{{else if eq .ElemType "string"}}
if wire != 2 {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
v, n, err := redisProtoReadBytes(b)
if err != nil {
	return err
}
b = b[n:]
p.{{.Name}} = append(p.{{.Name}}, string(v))
{{else if eq .ElemType "[]byte"}}
if wire != 2 {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
v, n, err := redisProtoReadBytes(b)
if err != nil {
	return err
}
b = b[n:]
p.{{.Name}} = append(p.{{.Name}}, v)
{{else if eq .ElemType "float32"}}
if wire == 5 {
	v, n, err := redisProtoReadFixed32(b)
	if err != nil {
		return err
	}
	b = b[n:]
	p.{{.Name}} = append(p.{{.Name}}, math.Float32frombits(v))
} else if wire == 2 {
	// packed：其他语言的 protoc 实现默认对 repeated 标量打包编码
	payload, n, err := redisProtoReadBytes(b)
	if err != nil {
		return err
	}
	b = b[n:]
	for len(payload) > 0 {
		v, m, err := redisProtoReadFixed32(payload)
		if err != nil {
			return err
		}
		payload = payload[m:]
		p.{{.Name}} = append(p.{{.Name}}, math.Float32frombits(v))
	}
} else {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
{{else if eq .ElemType "float64"}}
if wire == 1 {
	v, n, err := redisProtoReadFixed64(b)
	if err != nil {
		return err
	}
	b = b[n:]
	p.{{.Name}} = append(p.{{.Name}}, math.Float64frombits(v))
} else if wire == 2 {
	payload, n, err := redisProtoReadBytes(b)
	if err != nil {
		return err
	}
	b = b[n:]
	for len(payload) > 0 {
		v, m, err := redisProtoReadFixed64(payload)
		if err != nil {
			return err
		}
		payload = payload[m:]
		p.{{.Name}} = append(p.{{.Name}}, math.Float64frombits(v))
	}
} else {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
{{else if eq .ElemType "bool"}}
if wire == 0 {
	v, n, err := redisProtoReadVarint(b)
	if err != nil {
		return err
	}
	b = b[n:]
	p.{{.Name}} = append(p.{{.Name}}, v != 0)
} else if wire == 2 {
	payload, n, err := redisProtoReadBytes(b)
	if err != nil {
		return err
	}
	b = b[n:]
	for len(payload) > 0 {
		v, m, err := redisProtoReadVarint(payload)
		if err != nil {
			return err
		}
		payload = payload[m:]
		p.{{.Name}} = append(p.{{.Name}}, v != 0)
	}
} else {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
{{else}}
// 枚举与整型元素（varint，兼容 packed 编码）
if wire == 0 {
	v, n, err := redisProtoReadVarint(b)
	if err != nil {
		return err
	}
	b = b[n:]
	p.{{.Name}} = append(p.{{.Name}}, {{.ElemType}}(v))
} else if wire == 2 {
	payload, n, err := redisProtoReadBytes(b)
	if err != nil {
		return err
	}
	b = b[n:]
	for len(payload) > 0 {
		v, m, err := redisProtoReadVarint(payload)
		if err != nil {
			return err
		}
		payload = payload[m:]
		p.{{.Name}} = append(p.{{.Name}}, {{.ElemType}}(v))
	}
} else {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
{{end}}
{{else if eq .Kind "map"}}
if wire != 2 {
	return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "{{.Name}}", wire)
}
entry, n, err := redisProtoReadBytes(b)
if err != nil {
	return err
}
b = b[n:]
var k {{.KeyType}}
var val {{.ElemType}}
for len(entry) > 0 {
	t2, m, err := redisProtoReadVarint(entry)
	if err != nil {
		return err
	}
	entry = entry[m:]
	switch t2 >> 3 {
	case 1: // map 键
{{if eq .KeyType "string"}}
		if t2&7 != 2 {
			return fmt.Errorf("protobuf 字段 %s map 键 wire type 错误: %d", "{{.Name}}", t2&7)
		}
		payload, m, err := redisProtoReadBytes(entry)
		if err != nil {
			return err
		}
		entry = entry[m:]
		k = string(payload)
{{else if eq .KeyType "bool"}}
		if t2&7 != 0 {
			return fmt.Errorf("protobuf 字段 %s map 键 wire type 错误: %d", "{{.Name}}", t2&7)
		}
		kv, m, err := redisProtoReadVarint(entry)
		if err != nil {
			return err
		}
		entry = entry[m:]
		k = kv != 0
{{else}}
		if t2&7 != 0 {
			return fmt.Errorf("protobuf 字段 %s map 键 wire type 错误: %d", "{{.Name}}", t2&7)
		}
		kv, m, err := redisProtoReadVarint(entry)
		if err != nil {
			return err
		}
		entry = entry[m:]
		k = {{.KeyType}}(kv)
{{end}}
	case 2: // map 值
{{if .ElemIsMsg}}
		if t2&7 != 2 {
			return fmt.Errorf("protobuf 字段 %s map 值 wire type 错误: %d", "{{.Name}}", t2&7)
		}
		payload, m, err := redisProtoReadBytes(entry)
		if err != nil {
			return err
		}
		entry = entry[m:]
		if err := val.UnmarshalRedisProto(payload); err != nil {
			return fmt.Errorf("protobuf 反序列化字段 %s 失败: %v", "{{.Name}}", err)
		}
{{else if eq .ElemType "string"}}
		if t2&7 != 2 {
			return fmt.Errorf("protobuf 字段 %s map 值 wire type 错误: %d", "{{.Name}}", t2&7)
		}
		payload, m, err := redisProtoReadBytes(entry)
		if err != nil {
			return err
		}
		entry = entry[m:]
		val = string(payload)
{{else if eq .ElemType "[]byte"}}
		if t2&7 != 2 {
			return fmt.Errorf("protobuf 字段 %s map 值 wire type 错误: %d", "{{.Name}}", t2&7)
		}
		payload, m, err := redisProtoReadBytes(entry)
		if err != nil {
			return err
		}
		entry = entry[m:]
		val = payload
{{else if eq .ElemType "float32"}}
		if t2&7 != 5 {
			return fmt.Errorf("protobuf 字段 %s map 值 wire type 错误: %d", "{{.Name}}", t2&7)
		}
		fv, m, err := redisProtoReadFixed32(entry)
		if err != nil {
			return err
		}
		entry = entry[m:]
		val = math.Float32frombits(fv)
{{else if eq .ElemType "float64"}}
		if t2&7 != 1 {
			return fmt.Errorf("protobuf 字段 %s map 值 wire type 错误: %d", "{{.Name}}", t2&7)
		}
		fv, m, err := redisProtoReadFixed64(entry)
		if err != nil {
			return err
		}
		entry = entry[m:]
		val = math.Float64frombits(fv)
{{else if eq .ElemType "bool"}}
		if t2&7 != 0 {
			return fmt.Errorf("protobuf 字段 %s map 值 wire type 错误: %d", "{{.Name}}", t2&7)
		}
		bv, m, err := redisProtoReadVarint(entry)
		if err != nil {
			return err
		}
		entry = entry[m:]
		val = bv != 0
{{else}}
		// 枚举与整型值（varint）
		if t2&7 != 0 {
			return fmt.Errorf("protobuf 字段 %s map 值 wire type 错误: %d", "{{.Name}}", t2&7)
		}
		ev, m, err := redisProtoReadVarint(entry)
		if err != nil {
			return err
		}
		entry = entry[m:]
		val = {{.ElemType}}(ev)
{{end}}
	default:
		m, err = redisProtoSkip(entry, t2&7)
		if err != nil {
			return err
		}
		entry = entry[m:]
	}
}
if p.{{.Name}} == nil {
	p.{{.Name}} = make(map[{{.KeyType}}]{{.ElemType}})
}
p.{{.Name}}[k] = val
{{end}}
{{end}}
`
