// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: redb.proto

package cmddb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type REDBKey int32

const (
	REDBKey_None REDBKey = 0
	REDBKey_User REDBKey = 1
)

// Enum value maps for REDBKey.
var (
	REDBKey_name = map[int32]string{
		0: "None",
		1: "User",
	}
	REDBKey_value = map[string]int32{
		"None": 0,
		"User": 1,
	}
)

func (x REDBKey) Enum() *REDBKey {
	p := new(REDBKey)
	*p = x
	return p
}

func (x REDBKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (REDBKey) Descriptor() protoreflect.EnumDescriptor {
	return file_redb_proto_enumTypes[0].Descriptor()
}

func (REDBKey) Type() protoreflect.EnumType {
	return &file_redb_proto_enumTypes[0]
}

func (x REDBKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use REDBKey.Descriptor instead.
func (REDBKey) EnumDescriptor() ([]byte, []int) {
	return file_redb_proto_rawDescGZIP(), []int{0}
}

var File_redb_proto protoreflect.FileDescriptor

const file_redb_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"redb.proto\x12\x04REDB*\x1d\n" +
	"\aREDBKey\x12\b\n" +
	"\x04None\x10\x00\x12\b\n" +
	"\x04User\x10\x01B.Z,github.com/beijian128/protoc-gen-redis/cmddbb\x06proto3"

var (
	file_redb_proto_rawDescOnce sync.Once
	file_redb_proto_rawDescData []byte
)

func file_redb_proto_rawDescGZIP() []byte {
	file_redb_proto_rawDescOnce.Do(func() {
		file_redb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redb_proto_rawDesc), len(file_redb_proto_rawDesc)))
	})
	return file_redb_proto_rawDescData
}

var file_redb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_redb_proto_goTypes = []any{
	(REDBKey)(0), // 0: REDB.REDBKey
}
var file_redb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_redb_proto_init() }
func file_redb_proto_init() {
	if File_redb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redb_proto_rawDesc), len(file_redb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_redb_proto_goTypes,
		DependencyIndexes: file_redb_proto_depIdxs,
		EnumInfos:         file_redb_proto_enumTypes,
	}.Build()
	File_redb_proto = out.File
	file_redb_proto_goTypes = nil
	file_redb_proto_depIdxs = nil
}
